version: '2'
services:
    nginx:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./html/:/var/www/html/
            - ./logs/:/var/log/nginx/
            - ./conf/nginx.default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        build:
            context: ./docker-files
            dockerfile: Dockerfile.php-fpm
        volumes:
            - ./html/:/var/www/html/
            - ./conf/php-fpm.php.ini:/usr/local/etc/php/php.ini
            - ./conf/php-fpm.www.conf:/etc/php/7.0/fpm/pool.d/www.conf
        links:
            - mysql

    mysql:
        image: mariadb
        ports:
            - 3306:3306 # Optional, for remote access.
        volumes:
            - ./mysql/:/var/lib/mysql
            ### Create database from this SQL file
            ### (No effect, if database files are already existed)
            - ./conf/sensors.sql:/docker-entrypoint-initdb.d/sensors.sql
        environment:
            ### Set username and passwords on new database files.
            ### (No effect, if database files are already existed)
            - MYSQL_ROOT_PASSWORD=sensors/root
            - MYSQL_DATABASE=sensors

    ## No SSL, may not safe to run on public server
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        links:
            - mysql:db

    python:
        build:
            context: ./docker-files
            dockerfile: Dockerfile.python
        ports:
            - 60002:60002/udp
        volumes:
            - ./python/:/root/
        links:
            - mysql

    python_old:
        build:
            context: ./docker-files
            dockerfile: Dockerfile.python_old
        ports:
            - 60001:60001/udp
        volumes:
            - ./python_old/:/root/
        links:
            - mysql

